export const CHANGE_PROFILE_NAME = 'CHANGE_PROFILE_NAME';
export const CHANGE_PROFILE_LASTNAME = 'CHANGE_PROFILE_LASTNAME';

export const START_PROFILE_LOADING = 'START_PROFILE_LOADING';
export const SUCCESS_PROFILE_LOADING = 'SUCCESS_PROFILE_LOADING';
export const ERROR_PROFILE_LOADING = 'ERROR_PROFILE_LOADING';